<a href="https://colab.research.google.com/github/nicoleromulo/LinearAlgebra/blob/main/ASSIGNMENT_6_ROMULO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Linear Algebra for ECE**
### ***Laboratory 6: Matrix Operations***
Now that you have a fundamental knowledge about representing and operating with vectors as well as the fundamentals of matrices, we'll try to the same operations with matrices and even more.


In [1]:
import numpy as np
import matplotlib.pyplot as plt 
%matplotlib inline

#### **Transposition**
One of the fundamental operations in matrix algebra is Transposition. The transpose of a matrix is done by flipping the values of its elements over its diagonals. With this, the rows and columns from the original matrix will be switched. So for a matrix $A$ its transpose is denoted as $A^T$. So for example:
$$
A=\begin{bmatrix} 1 & 2 & 5 \\ 5 & -1 & 0 \\ 0 & -3 & 3\end{bmatrix} \\
A^T=\begin{bmatrix} 1 & 2 & 5 \\ 5 & -1 & 0 \\ 0 & -3 & 3\end{bmatrix}
$$
This can now be achieved programmatically by using np.transpose() or using the T method.



In [2]:
A = np.array ([
               [1, 2, 5],
               [5, -1, 0],
               [0, -3, 3]
])
A

array([[ 1,  2,  5],
       [ 5, -1,  0],
       [ 0, -3,  3]])

In [3]:
AT1 = np.transpose(A)
AT1

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [4]:
AT2 = A.T
AT2

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [5]:
np.array_equiv(AT1, AT2)

True

In [6]:
B = np.array ([
               [1, 2, 3, 4],
               [1, 0, 2, 1]
])
B.shape

(2, 4)

In [7]:
np.transpose(B) .shape

(4, 2)

In [8]:
B.T. shape

(4, 2)

##### **Own matrix to test transposition.**

In [9]:
N = np.array ([
               [2, 3, 4, 5],
               [2, 6, 9, 2],
               [8, 1, 0, -2]
])
N.shape

(3, 4)

In [10]:
np.transpose(N).shape

(4, 3)

In [11]:
N.T.shape

(4, 3)

In [12]:
NT = N.T
NT 

array([[ 2,  2,  8],
       [ 3,  6,  1],
       [ 4,  9,  0],
       [ 5,  2, -2]])

####**Dot Product/ Inner Product**
If you recall the dot product from laboratory activity before, we will try to implement the same operation with matrices. In matrix dot product we are going to get the sum of products of the vectors by row-column pairs. So if we have two matrices $X$ and $Y$:

$$
X=\begin{bmatrix} X_{(0, 0)}  & X_{(0, 1)} \\ X_{(1, 0)} & X_{(1, 1)}\end{bmatrix}, Y=\begin{bmatrix} Y_{(0, 0)}& Y_{(0, 1)}& Y_{(1, 0)}& Y_{(1, 1)}\end{bmatrix}
$$




The dot product will then be computed as:
$$
X\cdot Y=\begin{bmatrix} X_{(0, 0)}*Y_{(0, 0)}+X_{(0, 1)}*Y_{(1, 0)}& X_{(0, 0)}*Y_{(0, 1)}+X_{(0, 1)}*Y_{(1, 1)}\\ X_{(1, 0)}*Y_{(0, 0)}+X_{(1, 1)}*Y_{(1, 0)} &X_{(1, 0)}*Y_{(0, 1)}+X_{(1, 1)}*Y_{(1, 1)}\end{bmatrix}, 
$$

So if we assign values to $X$ and $Y$:
$$
X=\begin{bmatrix} 1 & 2\\ 0 & 1\end{bmatrix}, Y=\begin{bmatrix}-1 & 0 & 2 & 2\end{bmatrix} \\
X\cdot Y=\begin{bmatrix} 1*-1+2*2 & 1*0+2*2\\ 0*-1+1*2 & 0*0+1*2\end{bmatrix} = \begin{bmatrix}3&4&2&2\end{bmatrix} 
$$

This could be achieved programmatically using np.dot(), np.matmul() or the @ operator.

In [13]:
X = np.array([
    [1,2],
    [0,1]
])
Y = np.array([
    [-1,0],
    [2,2]
])

In [14]:
np.array_equiv(X,Y)

False

In [15]:
np.dot(X,Y)

array([[3, 4],
       [2, 2]])

In [16]:
X.dot(Y)

array([[3, 4],
       [2, 2]])

In [17]:
X @ Y

array([[3, 4],
       [2, 2]])

In [18]:
np.matmul(X, Y)

array([[3, 4],
       [2, 2]])

In [19]:
N = np.array([
    [-2, 3, 4],
    [0, 1, -5],
    [8, -4, 1]
])
R = np.array([
    [-2 , 0, 2],
    [2, 5, -6],
    [4, -3, 1]
])


In [20]:
N @ R

array([[ 26,   3, -18],
       [-18,  20, -11],
       [-20, -23,  41]])

In [21]:
np.dot(N, R)

array([[ 26,   3, -18],
       [-18,  20, -11],
       [-20, -23,  41]])

In [22]:
N.dot(R)

array([[ 26,   3, -18],
       [-18,  20, -11],
       [-20, -23,  41]])

In [23]:
np.matmul(N, R)

array([[ 26,   3, -18],
       [-18,  20, -11],
       [-20, -23,  41]])

In [24]:
np.dot(N, R)

array([[ 26,   3, -18],
       [-18,  20, -11],
       [-20, -23,  41]])

In matrix dot products there are additional rules compared with vector dot products. Since vector dot products were just in one dimension there are less restrictions. Since now we are dealing with Rank 2 vectors we need to consider some rules:

###**Rule 1: The inner dimensions of the two matrices in question must be the same.**
So given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:

$$
A=\begin{bmatrix}2&4&\\5&-2\\0&1\end{bmatrix}, B=\begin{bmatrix}1&13&3&-1&-2\end{bmatrix}, C=\begin{bmatrix}0&1&11&1&2\end{bmatrix} 
$$


So in this case $N$ has a shape of $(3,2)$, $R$ has a shape of $(3,2)$ and $V$ has a shape of $(2,3)$. So the only matrix pairs that is eligible to perform dot product is matrices $N \cdot V$, or $R \cdot V$.

```
# This is formatted as code
```



In [25]:
N = np.array([
    [-2, 3],
    [0, 1],
    [8, -4]
])
R = np.array([
    [-2 , 0],
    [2, 5],
    [4, -3]    
])
V= np.array([
    [-2 , 0, 2],
    [2, 5, -6]
])      
print(N.shape)
print(R.shape) 
print(V.shape)

(3, 2)
(3, 2)
(2, 3)


In [26]:
N @ V

array([[ 10,  15, -22],
       [  2,   5,  -6],
       [-24, -20,  40]])

In [27]:
R @ V

array([[  4,   0,  -4],
       [  6,  25, -26],
       [-14, -15,  26]])

In [28]:
N = np.array([
    [-2, 3, 4]
]) 
R = np.array([
    [-2, 3, 4]
])
print(N.shape)
print(R.shape)

   

(1, 3)
(1, 3)


In [29]:
N.T @ R

array([[ 4, -6, -8],
       [-6,  9, 12],
       [-8, 12, 16]])

In [30]:
R @ N.T

array([[29]])

In [31]:
X = np.array([
    [1,2,3,0]
])
Y = np.array([
    [1,0,4,-1]
])
print(X.shape)
print(Y.shape)

(1, 4)
(1, 4)


In [32]:
Y.T @ X

array([[ 1,  2,  3,  0],
       [ 0,  0,  0,  0],
       [ 4,  8, 12,  0],
       [-1, -2, -3,  0]])

In [33]:
X @ Y.T

array([[13]])

**And you can see that when you try to multiply A and B, it returns ValueError pertaining to matrix shape mismatch.**

####**Rule 2: Dot Product has special properties**
Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:
1. $A \cdot B \neq B \cdot A$
2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
3. $A\cdot(B+C) = A\cdot B + A\cdot C$
4. $(B+C)\cdot A = B\cdot A + C\cdot A$
5. $A\cdot I = A$
6. $A\cdot \emptyset = \emptyset$

In [34]:

A = np.array([
    [3,2,1],
    [4,5,1],
    [1,1,1]
])
B = np.array([
    [4,1,6],
    [4,1,9],
    [1,4,8]
])
C = np.array([
    [1,1,0],
    [0,1,1],
    [1,0,1]
])

In [35]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
A.dot(np.eye(3))

array([[3., 2., 1.],
       [4., 5., 1.],
       [1., 1., 1.]])

In [37]:
np.array_equal(A@B, B@A)

False

In [38]:
E = A @ (B @ C)
E

array([[ 65,  30,  53],
       [114,  50,  90],
       [ 32,  15,  29]])

In [39]:
F = (A @ B) @ C
F

array([[ 65,  30,  53],
       [114,  50,  90],
       [ 32,  15,  29]])

In [40]:
np.array_equal(E, X)

False

In [41]:
np.array_equiv(E, F)

True

In [42]:
np.eye(A)

TypeError: ignored

In [43]:
A @ E

array([[455, 205, 368],
       [862, 385, 691],
       [211,  95, 172]])

In [44]:
z_mat = np.zeros(A.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [45]:
a_dot_z = A.dot(np.zeros(A.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [46]:
np.array_equal(a_dot_z,z_mat)

True

In [47]:
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

#### **Determinant** 

A determinant is a scalar value derived from a square matrix. The determinant is a fundamental and important value used in matrix algebra. Although it will not be evident in this laboratory on how it can be used practically, but it will be reatly used in future lessons.

The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:

$$
A = \begin{bmatrix}a_{(0,0)}&amp;a_{(0,1)}\\a_{(1,0)}&amp;a_{(1,1)}\end{bmatrix}
$$

We can compute for the determinant as:
$$
|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}
$$

So if we have $A$ as:
$$
A = \begin{bmatrix}1&amp;4\\0&amp;3\end{bmatrix}, |A| = 3
$$

But you might wonder how about square matrices beyond the shape $(2,2)$? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. We can achieve this by using np.linalg.det().


In [48]:
A = np.array ([
    [1,4],
    [0,3]       
])
np.linalg.det(A)

3.0000000000000004

In [49]:
B = np.array ([
    [1,5,2],
    [3,-1,-1],
    [0,-2,1]       
])
np.linalg.det(A)

3.0000000000000004

In [50]:
B = np.array([
    [1,3,5,6],
    [0,3,1,3],
    [3,1,8,2],
    [5,2,6,8]
])
np.linalg.det(B)

-235.0000000000002

Inverse
The inverse of a matrix is another fundamental operation in matrix algebra. Determining the inverse of a matrix let us determine if its solvability and its characteristic as a system of linear equation — we'll expand on this in the nect module. Another use of the inverse matrix is solving the problem of divisibility between matrices. Although element-wise division exists but dividing the entire concept of matrices does not exists. Inverse matrices provides a related operation that could have the same concept of "dividing" matrices.

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:
$$
M = \begin{bmatrix}1&7\\-3&5\end{bmatrix}
$$

First, we need to get the determinant of $M$.
$$
|M| = (1)(5)-(-3)(7) = 26
$$

Next, we need to reform the matrix into the inverse form:
$$
M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} & -m_{(0,1)} \\ -m_{(1,0)} &; m_{(0,0)}\end{bmatrix}
$$

So that will be:
$$
M^{-1} = \frac{1}{26} \begin{bmatrix} 5 & -7 \\ 3 & 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} & \frac{-7}{26} \\ \frac{3}{26} & \frac{1}{26}\end{bmatrix}
$$

For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use np.linalg.inv().

In [51]:
M = np.array([
    [1,7],
    [-3, 5]
])

np.array(M @ np.linalg.inv(M), dtype=int)

array([[1, 0],
       [0, 1]])

In [52]:
P = np.array([
              [6, 9, 0],
              [4, 2, -1],
              [3, 6, 7]
])
Q = np.linalg.inv(P)
Q

array([[-0.12578616,  0.39622642,  0.05660377],
       [ 0.19496855, -0.26415094, -0.03773585],
       [-0.11320755,  0.05660377,  0.1509434 ]])

In [54]:
P @ Q

array([[ 1.00000000e+00, -5.55111512e-17, -6.93889390e-18],
       [ 8.32667268e-17,  1.00000000e+00, -2.77555756e-17],
       [ 2.77555756e-17, -1.38777878e-17,  1.00000000e+00]])

In [53]:
N = np.array([
    [18,5,23,1,0,33,5],
    [0,45,0,11,2,4,2],
    [5,9,20,0,0,0,3],
    [1,6,4,4,8,43,1],
    [8,6,8,7,1,6,1],
    [-5,15,2,0,0,6,-30],
    [-2,-5,1,2,1,20,12],
])
N_inv = np.linalg.inv(N)
np.array(N @ N_inv,dtype=int)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1]])

To validate the wether if the matric that you have solved is really the inverse, we follow this dot product property for a matrix $M$:

$$
M\cdot M^{-1} = I
$$

In [55]:
squad = np.array([
    [1.0, 1.0, 0.5],
    [0.7, 0.7, 0.9],
    [0.3, 0.3, 1.0]
])
weights = np.array([
    [0.2, 0.2, 0.6]
])
p_grade = squad @ weights.T
p_grade

array([[0.7 ],
       [0.82],
       [0.72]])

###**Activity**
####**Task 1**
Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$. In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [56]:
X = np.array([
          [2,6,7],
          [3,4,8],
          [0,9,2]
])
Y = np.array([
          [1,3,4],
          [2,6,4],
          [3,6,1]
])

Z = np.array([
          [0,2,3],
          [9,7,4],
          [6,3,2]
])

In [57]:
X1 = X @ Y
X1

array([[35, 84, 39],
       [35, 81, 36],
       [24, 66, 38]])

In [58]:
Y1 = Y @ X
Y1

array([[11, 54, 39],
       [22, 72, 70],
       [24, 51, 71]])

In [59]:
np.array_equiv(X1,Y1)

False

In [60]:
X2 = X @ (Y @ Z)

In [61]:
Y2 = (X @ Y) @ Z

In [62]:
np.array_equal(X2,Y2)

True

In [63]:
X3 = X @ (Y + Z)
X3

array([[131, 151,  83],
       [119, 139,  77],
       [117, 135,  78]])

In [64]:
Y3 = X @ Y + X @ Z
Y3

array([[131, 151,  83],
       [119, 139,  77],
       [117, 135,  78]])

In [65]:
np.array_equal(X3,Y3)

True

In [66]:
X4 = (Y + Z) @ X

In [67]:
Y4 = Y @ X + Z @ X
Y4

array([[ 17,  89,  61],
       [ 61, 190, 197],
       [ 45, 117, 141]])

In [68]:
np.array_equal(X4,Y4)

True

In [72]:
X5 = X @ Y5
X5

array([[2., 6., 7.],
       [3., 4., 8.],
       [0., 9., 2.]])

In [71]:
Y5 = np.eye(3)
Y5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [74]:
np.array_equal(X5,Y5)

False

In [73]:
X6 = np.zeros(X.shape)
X6

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [75]:
Y6 = X.dot(np.zeros(X.shape))
Y6

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [76]:
np.array_equal(X6,Y6)

True

##**Conclusion**
*For your conclusion synthesize the concept and application of the laboratory. Briefly discuss what you have learned and achieved in this activity.*


This laboratory aims to broaden the knowledge of each students not just the basics but also the complex commands that can help us engineering students. I therefor conclude that i am familiarized with the matrix operations as well as i am practiced how to use and create different shapes of matrices and apply a various operations on it. I learned that you can use a single matrix but can be applied on different operations, so that you can get various results such as dot product, determinants, inverse and many more. All you have to remember is their respective command and proper execution.